branch-defaults:
  vanilla:
    environment: arkamatch-1
environment-defaults:
  arkamatch-1:
    branch: null
    repository: null
global:
  application_name: arkamatch
  default_ec2_keyname: arkamatch
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Puma with Ruby 2.5
    running on 64bit Amazon Linux/2.11.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
